"""AppealAgent port tests.

Goldens generated by running the ORIGINAL healthflow implementation's full
process_appeal flow (Claude mocked) against the fixture below — they prove a
byte-identical refine prompt, identical DenialParser/DenialCodeDB outputs,
and lock the phi_redacted audit contract. The appeal letter is not goldened
because AppealWriter stamps the current date; test_appeal_writer.py covers it.
"""
import json
from pathlib import Path

from helpers import RecordingAuditSink, RecordingInvocationTracker, make_mock_client

from healthflow_agents.agents.appeal_agent import AppealAgent

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "agents_4.json").read_text()
)["appeal"]

SAMPLE_DENIAL = (
    "Patient: John Smith\n"
    "Member ID: ABC123456\n"
    "DOB: 01/15/1960\n"
    "Date of denial: 03/15/2026\n"
    "\n"
    "Dear John Smith,\n"
    "\n"
    "Your claim for MRI of lumbar spine has been denied.\n"
    "Denial code: CO-50. The service is not deemed medically necessary.\n"
    "Per LCD L35936, this service does not meet coverage criteria.\n"
    "You have 60 days to file an appeal.\n"
)


# --- Golden smoke tests: identical prompts + tool outputs vs. the original ---


def test_system_prompt_matches_original_verbatim():
    agent = AppealAgent(client=make_mock_client())
    assert agent.system_prompt == GOLDENS["system_prompt"]


def test_process_appeal_sends_golden_prompt_and_matches_original_outputs():
    mock_client = make_mock_client("REFINED")
    agent = AppealAgent(client=mock_client)

    analysis, argument, letter, refined = agent.process_appeal(SAMPLE_DENIAL, "")

    kwargs = mock_client.messages.create.call_args.kwargs
    assert kwargs["system"] == GOLDENS["system_prompt"]
    assert kwargs["messages"] == [{"role": "user", "content": GOLDENS["user_prompt"]}]
    assert kwargs["model"] == GOLDENS["model_sent"] == "claude-opus-4-8"
    assert kwargs["max_tokens"] == GOLDENS["max_tokens_sent"] == 1024
    # DenialParser + DenialCodeDB outputs identical to the original.
    assert analysis.model_dump() == GOLDENS["analysis"]
    assert argument.model_dump() == GOLDENS["argument"]
    # Output shape: (DenialAnalysis, CoverageArgument, str, str).
    assert isinstance(letter, str) and isinstance(refined, str)
    assert refined == "REFINED"


def test_phi_redacted_audit_event_shape_preserved():
    """HealthFlow's audit consumers depend on this event name + payload shape."""
    audit = RecordingAuditSink()
    tracker = RecordingInvocationTracker()
    agent = AppealAgent(
        client=make_mock_client("REFINED"),
        audit_sink=audit,
        invocation_tracker=tracker,
    )
    agent.process_appeal(SAMPLE_DENIAL, "")

    assert audit.event_types() == [
        "phi_redacted",
        "denial_parsed",
        "tool_called",
        "recommendation_generated",
        "appeal_generated",
    ]
    # Exact payload observed from the original implementation's audit stream.
    assert audit.events[0][1] == {
        "count": 4,
        "types": ["[DOB]", "[MEMBER_ID]", "[PATIENT_NAME]"],
    }
    assert tracker.calls == [
        {"agent": "appeal", "event_type": "process_appeal", "model": "claude-opus-4-8"}
    ]
    assert tracker.records[0].details["code"] == "CO-50"
    assert tracker.records[0].details["code_found_in_db"] is True


# --- Ported from healthflow/tests/agents/test_appeal_agent.py ---


def test_full_flow_returns_all_components():
    agent = AppealAgent(
        client=make_mock_client("Additional appeal suggestion: request peer-to-peer review.")
    )
    analysis, argument, letter, recommendation = agent.process_appeal(SAMPLE_DENIAL, "")

    assert analysis.denial_reason_code == "CO-50"
    assert argument.cms_rule != ""
    assert len(argument.common_appeal_grounds) > 0
    assert "[PATIENT_NAME]" in letter
    assert recommendation != ""


def test_claude_receives_redacted_text_only():
    mock_client = make_mock_client("Suggestion")
    agent = AppealAgent(client=mock_client)
    agent.process_appeal(SAMPLE_DENIAL, "")

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "John Smith" not in user_msg
    assert "ABC123456" not in user_msg
    assert "01/15/1960" not in user_msg
    assert "[PATIENT_NAME]" in user_msg or "CO-50" in user_msg


def test_system_prompt_prohibits_medical_advice():
    mock_client = make_mock_client("Suggestion")
    agent = AppealAgent(client=mock_client)
    agent.process_appeal(SAMPLE_DENIAL, "")

    system = mock_client.messages.create.call_args.kwargs["system"]
    assert "medical advice" in system.lower()
    assert "guarantee" in system.lower()


def test_unknown_code_uses_fallback():
    agent = AppealAgent(client=make_mock_client("Review your appeal rights."))
    denial_text = "Your claim has been denied. Code: CO-9999. The service is not covered."
    analysis, argument, letter, recommendation = agent.process_appeal(denial_text, "")

    assert analysis.denial_reason_code == "CO-9999"
    assert argument.cms_rule != ""
    assert len(argument.common_appeal_grounds) > 0
    assert "[PATIENT_NAME]" in letter


def test_process_appeal_sends_redacted_text_to_claude():
    """The denial text reaching client.messages.create must be redacted."""
    mock_client = make_mock_client("Refined advice.")
    agent = AppealAgent(client=mock_client)

    agent.process_appeal(
        denial_text="Patient: Emily Dickinson denied. DOB: 03/04/1950.",
        additional_context="",
    )

    sent_prompt = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "Emily Dickinson" not in sent_prompt
    assert "[PATIENT_NAME]" in sent_prompt
    assert "03/04/1950" not in sent_prompt
    assert "[DOB]" in sent_prompt
