"""ComparisonAgent port tests.

The golden strings in tests/goldens/comparison_agent.json were generated by
running the ORIGINAL healthflow.agents.comparison_agent implementation
(health-insurance-agent repo) against the fixture below — the smoke tests
prove the ported agent produces byte-identical prompts.
"""
import json
from contextlib import contextmanager
from pathlib import Path
from unittest.mock import MagicMock

from healthflow_agents.agents.comparison_agent import (
    _TEST_MODE_RECOMMENDATION,
    ComparisonAgent,
)
from healthflow_agents.contracts import PlanSummary
from healthflow_agents.core.logging import StdoutAuditSink, StdoutInvocationTracker
from healthflow_agents.redaction.prompt_inputs import ComparisonPromptInput

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "comparison_agent.json").read_text()
)

SAMPLE_PLANS = [
    PlanSummary(
        plan_name="Aetna Medicare Eagle Plus (HMO)",
        plan_id="H3312-034",
        monthly_premium=0.00,
        annual_deductible=250.00,
        out_of_pocket_max=4500.00,
        star_rating=4.5,
        plan_type="HMO",
        drug_coverage=True,
        estimated_medication_costs={"Metformin": 5.0},
        estimated_procedure_costs={"MRI": 150.0},
    ),
    PlanSummary(
        plan_name="UHC Medicare Advantage Choice (PPO)",
        plan_id="H2228-050",
        monthly_premium=25.00,
        annual_deductible=150.00,
        out_of_pocket_max=5500.00,
        star_rating=4.0,
        plan_type="PPO",
        drug_coverage=True,
        estimated_medication_costs={"Metformin": 10.0},
        estimated_procedure_costs={"MRI": 250.0},
    ),
]


def make_agent(response_text: str = "Recommendation", **kwargs) -> tuple[ComparisonAgent, MagicMock]:
    """Agent with a mocked Anthropic client returning `response_text`."""
    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_response.content = [MagicMock(text=response_text)]
    mock_client.messages.create.return_value = mock_response
    return ComparisonAgent(client=mock_client, **kwargs), mock_client


class RecordingAuditSink:
    def __init__(self) -> None:
        self.events: list[tuple[str, dict]] = []

    def log(self, event_type: str, details: dict) -> None:
        self.events.append((event_type, details))


class RecordingInvocationTracker:
    def __init__(self) -> None:
        self.records: list[MagicMock] = []
        self.calls: list[dict] = []

    @contextmanager
    def __call__(self, *, agent: str, event_type: str, model: str | None = None):
        self.calls.append({"agent": agent, "event_type": event_type, "model": model})
        record = MagicMock()
        record.details = {}
        self.records.append(record)
        yield record


# --- Golden smoke tests: identical prompt strings vs. the original ---


def test_system_prompt_matches_original_verbatim():
    agent, _ = make_agent()
    assert agent.system_prompt == GOLDENS["system_prompt"]


def test_build_prompt_matches_original_verbatim_with_meds_and_procedures():
    agent, _ = make_agent()
    prompt_input = ComparisonPromptInput(
        plans=SAMPLE_PLANS,
        age=65,
        income_level="low",
        medications=["Metformin"],
        procedures=["MRI"],
    )
    assert agent._build_prompt(prompt_input) == GOLDENS["user_prompt_full"]


def test_build_prompt_matches_original_verbatim_without_meds_or_procedures():
    agent, _ = make_agent()
    prompt_input = ComparisonPromptInput(
        plans=SAMPLE_PLANS, age=65, income_level="low", medications=[], procedures=[]
    )
    assert agent._build_prompt(prompt_input) == GOLDENS["user_prompt_bare"]


def test_recommend_sends_golden_prompts_and_returns_text_output():
    agent, mock_client = make_agent("Plan A is the best choice for your budget.")
    result = agent.recommend(
        plans=SAMPLE_PLANS,
        age=65,
        income_level="low",
        medications=["Metformin"],
        procedures=["MRI"],
    )

    kwargs = mock_client.messages.create.call_args.kwargs
    assert kwargs["system"] == GOLDENS["system_prompt"]
    assert kwargs["messages"] == [
        {"role": "user", "content": GOLDENS["user_prompt_full"]}
    ]
    assert kwargs["model"] == "claude-haiku-4-5"
    assert kwargs["max_tokens"] == 1024
    # Output shape: plain string, same as the original agent.
    assert isinstance(result, str)
    assert result == "Plan A is the best choice for your budget."


# --- Ported from healthflow/tests/agents/test_comparison_agent.py ---


def test_agent_returns_recommendation():
    agent, mock_client = make_agent("Plan A is the best choice for your budget.")
    result = agent.recommend(
        plans=SAMPLE_PLANS,
        age=65,
        income_level="low",
        medications=["Metformin"],
        procedures=["MRI"],
    )
    assert "Plan A" in result
    mock_client.messages.create.assert_called_once()


def test_agent_sends_system_prompt():
    agent, mock_client = make_agent()
    agent.recommend(plans=SAMPLE_PLANS, age=65, income_level="low")

    call_kwargs = mock_client.messages.create.call_args
    assert "system" in call_kwargs.kwargs
    assert "medical advice" in call_kwargs.kwargs["system"].lower()


def test_agent_includes_plan_data_in_prompt():
    agent, mock_client = make_agent()
    agent.recommend(plans=SAMPLE_PLANS, age=65, income_level="low")

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "Aetna" in user_msg
    assert "H3312-034" in user_msg


def test_agent_includes_cost_data_when_provided():
    agent, mock_client = make_agent()
    agent.recommend(
        plans=SAMPLE_PLANS,
        age=65,
        income_level="low",
        medications=["Metformin"],
        procedures=["MRI"],
    )

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "Metformin" in user_msg
    assert "MRI" in user_msg


def test_agent_stubs_anthropic_call_in_test_mode(monkeypatch):
    """In HEALTHFLOW_TEST_MODE, recommend() must NOT call the Anthropic API.

    The e2e docker stack runs with a fake API key; without a stub path,
    /compare returns 500 because the API rejects the key.
    """
    monkeypatch.setenv("HEALTHFLOW_TEST_MODE", "1")
    agent, mock_client = make_agent()
    result = agent.recommend(plans=SAMPLE_PLANS, age=65, income_level="low")

    assert isinstance(result, str) and result
    assert result == _TEST_MODE_RECOMMENDATION
    mock_client.messages.create.assert_not_called()


# --- Injection pattern: audit + invocation contracts preserved ---


def test_injected_sinks_receive_original_event_stream():
    audit = RecordingAuditSink()
    tracker = RecordingInvocationTracker()
    agent, _ = make_agent("Some recommendation", audit_sink=audit, invocation_tracker=tracker)

    agent.recommend(plans=SAMPLE_PLANS, age=65, income_level="low")

    assert [e for e, _ in audit.events] == ["tool_called", "recommendation_generated"]
    assert audit.events[0][1] == {"tool": "claude_api", "model": "claude-haiku-4-5"}
    assert audit.events[1][1] == {"length": len("Some recommendation")}
    assert tracker.calls == [
        {"agent": "comparison", "event_type": "recommend", "model": "claude-haiku-4-5"}
    ]
    assert tracker.records[0].details == {
        "length": len("Some recommendation"),
        "plans": 2,
    }


def test_test_mode_stub_audit_payload_preserved(monkeypatch):
    monkeypatch.setenv("HEALTHFLOW_TEST_MODE", "1")
    audit = RecordingAuditSink()
    tracker = RecordingInvocationTracker()
    agent, _ = make_agent(audit_sink=audit, invocation_tracker=tracker)

    agent.recommend(plans=SAMPLE_PLANS, age=65, income_level="low")

    assert audit.events == [
        (
            "recommendation_generated",
            {"length": len(_TEST_MODE_RECOMMENDATION), "stubbed": True},
        )
    ]
    assert tracker.records[0].details == {
        "length": len(_TEST_MODE_RECOMMENDATION),
        "stubbed": True,
    }


def test_standalone_defaults_require_no_injection(monkeypatch):
    """With no injected sinks the agent runs on stdout defaults."""
    monkeypatch.setenv("ANTHROPIC_API_KEY", "test-key-not-real")
    agent = ComparisonAgent()
    assert isinstance(agent.audit, StdoutAuditSink)
    assert isinstance(agent.invocations, StdoutInvocationTracker)
    assert agent.model == "claude-haiku-4-5"
