"""TranslationAgent port tests.

Goldens generated by running the ORIGINAL healthflow implementation against
the fixtures below — they prove byte-identical prompts, including through the
redaction path, and lock the phi_redacted audit contract.
"""
import json
from pathlib import Path

from helpers import RecordingAuditSink, make_mock_client

from healthflow_agents.agents.translation_agent import TranslationAgent
from healthflow_agents.contracts import DocumentSection

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "agents_4.json").read_text()
)["translation"]

SAMPLE_SECTIONS = [
    DocumentSection(
        title="EMERGENCY CARE",
        content="Emergency room: $90 copay (waived if admitted)\nAmbulance: $250 copay",
    ),
    DocumentSection(
        title="INPATIENT HOSPITAL CARE",
        content="You pay $250 copay per day for days 1-5.\nPrior authorization required.",
    ),
]


# --- Golden smoke tests: identical prompt strings vs. the original ---


def test_system_prompt_matches_original_verbatim():
    agent = TranslationAgent(client=make_mock_client())
    assert agent.system_prompt == GOLDENS["system_prompt"]


def test_translate_sends_golden_prompts_and_returns_original_shape():
    mock_client = make_mock_client("The ER copay is $90.")
    agent = TranslationAgent(client=mock_client)

    answer, section_titles = agent.translate(
        sections=SAMPLE_SECTIONS, question="What is the ER copay?"
    )

    kwargs = mock_client.messages.create.call_args.kwargs
    assert kwargs["system"] == GOLDENS["system_prompt"]
    assert kwargs["messages"] == [{"role": "user", "content": GOLDENS["user_prompt"]}]
    assert kwargs["model"] == "claude-sonnet-4-6"
    assert kwargs["max_tokens"] == 1024
    # Output shape: (str, list[str]), same as the original agent.
    assert answer == "The ER copay is $90."
    assert section_titles == ["EMERGENCY CARE", "INPATIENT HOSPITAL CARE"]


def test_redacted_prompt_matches_original_verbatim():
    mock_client = make_mock_client("Answer.")
    agent = TranslationAgent(client=mock_client)
    agent.translate(
        sections=[
            DocumentSection(title="Eligibility", content="Patient: Robert Frost is eligible.")
        ],
        question="Dear Robert Frost, what is the copay?",
    )

    sent_prompt = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert sent_prompt == GOLDENS["user_prompt_redacted_fixture"]


def test_phi_redacted_audit_event_shape_preserved():
    """HealthFlow's audit consumers depend on this event name + payload shape."""
    audit = RecordingAuditSink()
    agent = TranslationAgent(client=make_mock_client("Answer."), audit_sink=audit)
    agent.translate(
        sections=[
            DocumentSection(title="Eligibility", content="Patient: Robert Frost is eligible.")
        ],
        question="Dear Robert Frost, what is the copay?",
    )

    assert audit.event_types() == [
        "phi_redacted",
        "tool_called",
        "recommendation_generated",
    ]
    assert audit.events[0][1] == GOLDENS["redaction_summary"]
    assert audit.events[0][1] == {"count": 2, "types": ["[PATIENT_NAME]"]}


# --- Ported from healthflow/tests/agents/test_translation_agent.py ---


def test_agent_returns_answer():
    mock_client = make_mock_client("The ER copay is $90.")
    agent = TranslationAgent(client=mock_client)
    answer, section_titles = agent.translate(
        sections=SAMPLE_SECTIONS,
        question="What is the ER copay?",
    )

    assert "ER copay" in answer or "$90" in answer
    mock_client.messages.create.assert_called_once()


def test_agent_returns_section_titles():
    agent = TranslationAgent(client=make_mock_client("The answer is..."))
    _, section_titles = agent.translate(
        sections=SAMPLE_SECTIONS,
        question="What is the ER copay?",
    )

    assert "EMERGENCY CARE" in section_titles
    assert "INPATIENT HOSPITAL CARE" in section_titles


def test_agent_sends_system_prompt_no_medical_advice():
    mock_client = make_mock_client("Answer")
    agent = TranslationAgent(client=mock_client)
    agent.translate(sections=SAMPLE_SECTIONS, question="test?")

    system = mock_client.messages.create.call_args.kwargs["system"]
    assert "medical advice" in system.lower()
    assert "plain" in system.lower() or "clear" in system.lower()


def test_agent_includes_sections_in_prompt():
    mock_client = make_mock_client("Answer")
    agent = TranslationAgent(client=mock_client)
    agent.translate(sections=SAMPLE_SECTIONS, question="What is the ER copay?")

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "EMERGENCY CARE" in user_msg
    assert "$90 copay" in user_msg


def test_agent_includes_question_in_prompt():
    mock_client = make_mock_client("Answer")
    agent = TranslationAgent(client=mock_client)
    agent.translate(sections=SAMPLE_SECTIONS, question="What is the ER copay?")

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "What is the ER copay?" in user_msg


def test_translate_sends_redacted_prompt_to_claude():
    """The user_prompt reaching client.messages.create must be redacted."""
    mock_client = make_mock_client("Answer.")
    agent = TranslationAgent(client=mock_client)
    sections = [
        DocumentSection(title="Eligibility", content="Patient: Robert Frost is eligible."),
    ]

    agent.translate(sections=sections, question="Dear Robert Frost, what is the copay?")

    sent_prompt = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "Robert Frost" not in sent_prompt
    assert "[PATIENT_NAME]" in sent_prompt
