"""CostCalculatorAgent port tests.

Goldens generated by running the ORIGINAL healthflow implementation (with the
drug sqlite DB absent, matching the standalone package) against the fixtures
below — they prove byte-identical prompts and identical CostModeler results.
"""
import json
from pathlib import Path

from helpers import make_mock_client

from healthflow_agents.agents.cost_calculator_agent import CostCalculatorAgent
from healthflow_agents.contracts import PlanSummary, PrescriptionInput, UsageInput

GOLDENS = json.loads(
    (Path(__file__).parent / "goldens" / "agents_4.json").read_text()
)["cost"]

SAMPLE_PLANS = [
    PlanSummary(
        plan_name="Expensive Plan",
        plan_id="H0001-001",
        monthly_premium=100.0,
        annual_deductible=500.0,
        out_of_pocket_max=8000.0,
        star_rating=3.0,
        plan_type="PPO",
        drug_coverage=True,
    ),
    PlanSummary(
        plan_name="Cheap Plan",
        plan_id="H0001-002",
        monthly_premium=0.0,
        annual_deductible=0.0,
        out_of_pocket_max=4000.0,
        star_rating=4.5,
        plan_type="HMO",
        drug_coverage=True,
    ),
]

SAMPLE_USAGE = UsageInput(
    doctor_visits_per_year=12,
    prescriptions=[PrescriptionInput(name="Metformin", fills_per_year=12)],
)


# --- Golden smoke tests: identical prompts + tool results vs. the original ---


def test_system_prompt_matches_original_verbatim():
    agent = CostCalculatorAgent(client=make_mock_client())
    assert agent.system_prompt == GOLDENS["system_prompt"]


def test_calculate_sends_golden_prompts_and_matches_original_results():
    mock_client = make_mock_client("Cheap Plan saves you money.")
    agent = CostCalculatorAgent(client=mock_client)

    results, recommendation = agent.calculate(SAMPLE_PLANS, SAMPLE_USAGE)

    kwargs = mock_client.messages.create.call_args.kwargs
    assert kwargs["system"] == GOLDENS["system_prompt"]
    assert kwargs["messages"] == [{"role": "user", "content": GOLDENS["user_prompt"]}]
    assert kwargs["model"] == "claude-haiku-4-5"
    assert kwargs["max_tokens"] == 1024
    # CostModeler output identical to the original implementation.
    assert [r.model_dump() for r in results] == GOLDENS["results"]
    # Output shape: (list[PlanCostResult], str), same as the original agent.
    assert isinstance(recommendation, str)


# --- Ported from healthflow/tests/agents/test_cost_calculator_agent.py ---


def test_agent_returns_sorted_results():
    agent = CostCalculatorAgent(client=make_mock_client("Cheap Plan saves you money."))
    results, recommendation = agent.calculate(SAMPLE_PLANS, SAMPLE_USAGE)

    assert results[0].plan_id == "H0001-002"
    assert results[0].total_annual_cost < results[1].total_annual_cost


def test_agent_calls_claude():
    mock_client = make_mock_client("Recommendation text.")
    agent = CostCalculatorAgent(client=mock_client)
    _, recommendation = agent.calculate(SAMPLE_PLANS, SAMPLE_USAGE)

    mock_client.messages.create.assert_called_once()
    assert recommendation == "Recommendation text."


def test_agent_system_prompt_no_medical_advice():
    mock_client = make_mock_client("Text")
    agent = CostCalculatorAgent(client=mock_client)
    agent.calculate(SAMPLE_PLANS, SAMPLE_USAGE)

    system = mock_client.messages.create.call_args.kwargs["system"]
    assert "medical advice" in system.lower()


def test_agent_prompt_includes_cost_data():
    mock_client = make_mock_client("Text")
    agent = CostCalculatorAgent(client=mock_client)
    agent.calculate(SAMPLE_PLANS, SAMPLE_USAGE)

    user_msg = mock_client.messages.create.call_args.kwargs["messages"][0]["content"]
    assert "Cheap Plan" in user_msg
    assert "Expensive Plan" in user_msg
    assert "Metformin" in user_msg
